### ISSUE TITLE
Can cause lag

### ISSUE THREAD

**Issue by cra0zy** [Tudmotu/gnome-shell-extension-clipboard-indicator#27]
Let me elaborate, if the person is running GNOME and Wayland, it will cause the shell to freeze/lag every time the extension checks the clipboard.

**Comment by Tudmotu** [comment]
Thank you for reporting!
Though I will have difficulties debugging this since I don't use wayland :(

**Comment by cra0zy** [comment]
> Though I will have difficulties debugging this since I don't use wayland :(

Point me to lines which are reading the clipboard, I'll see what I can find.

**Comment by Tudmotu** [comment]
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/extension.js#L247
This function is invoked every couple of seconds, and checks if the clipboard has updated.

**Comment by cra0zy** [comment]
So, it seems that the "clipboard.get_text" function by itself is causing the lag.

**Comment by Tudmotu** [comment]
Does your shell freeze every second? Or only when you copy something?

**Comment by cra0zy** [comment]
Every second.

**Comment by bulletmark** [comment]
I'm on Arch which includes GNOME 3.20 in the stock packages now. I tried Wayland today given it is just a simple option on the GDM login window and found everything in my environment seems to work fine except this extension causes gnome-shell to use excessive CPU. This is very easy to see by bringing up a terminal window and running htop while I switch the extension on and off via tweak tool. Doing the same thing under standard Xorg shows no such problem, nor does switching off/on any of my other extensions.

**Comment by Tudmotu** [comment]
@bulletmark  - do you have the same freezing issue as described above, or only the high-cpu?
I must admit I forgot about this issue. :P 

I'll try and take a look in the next few days.

**Comment by bulletmark** [comment]
Under Wayland, htop shows gnome-shell using about 1% CPU in the quiescent state with little happening. Enable this extension and gnome-shell settles to 10% CPU. Disable it and it settles back to 1% .. etc. Doing the same sequence under Xorg gnome-shell stays at the 1% whether the extension is enabled or not. I had noticed that gnome-shell was laggy which is why I went looking for this issue.

**Comment by Tudmotu** [comment]
OK, thanks. There's of course the chance that this is an issue with Gnome and not the extension (the Wayland implementation is still not completely stable). I will investigate it further and will update in here.

**Comment by cra0zy** [comment]
This got fixed in the newest version of GNOME/Gtk :)

**Comment by Tudmotu** [comment]
Thanks for the update @cra0zy ! :)
@bulletmark - might this be resolved for you as well now?

**Comment by bulletmark** [comment]
@Tudmotu I am running up to date Arch and just switched back to Wayland to check this but it is still the same.

**Comment by junrrein** [comment]
I can confirm this still happens under Wayland. I'm running gnome-shell 3.22 under Opensuse Tumbleweed.

**Comment by bulletmark** [comment]
Stock Arch updated gnome-shell from 3.20.4 to  to 3.22.1 today and I don't see this problem anymore under Wayland.

**Comment by junrrein** [comment]
gnome-shell 3.22.1 mentions in its changelog:

    Fix feedback loop between StClipboard and X11 bridge

which seems directly relevant to the issue.

I'll update once this new version hits Tumbleweed, which could take some days.

**Comment by junrrein** [comment]
I can confirm, gnome-shell 3.22.1 fixes this issue.
